// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateRecentDocument(arg1:string):Promise<void>;

export function CancelQuitRequest():Promise<void>;

export function CancelUpdateDownload():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearRecentItems():Promise<void>;

export function CloseWebDAVDocument(arg1:string,arg2:string):Promise<void>;

export function CloseWebDAVWorkspace(arg1:string):Promise<void>;

export function CloseWorkspace(arg1:string):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function ConnectWebDAV(arg1:main.WebDAVConfig):Promise<main.Workspace>;

export function DownloadUpdate(arg1:string):Promise<main.UpdateDownload>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetLanguageSettings():Promise<main.LanguageState>;

export function LaunchUpdateInstaller():Promise<void>;

export function ListWebDAVDirectory(arg1:string,arg2:string):Promise<main.WorkspaceDirectory>;

export function LoadInitialDocument(arg1:string):Promise<main.Document>;

export function OpenDirectory():Promise<main.Workspace>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile():Promise<main.Document>;

export function OpenRecentDirectory(arg1:string):Promise<main.Workspace>;

export function OpenRecentFile(arg1:string):Promise<main.Document>;

export function OpenSourceRepository():Promise<void>;

export function OpenUpdatePage():Promise<void>;

export function OpenWebDAVFile(arg1:string,arg2:string):Promise<main.Document>;

export function OpenWorkspaceFile(arg1:string,arg2:string):Promise<main.Document>;

export function OverwriteWebDAVFile(arg1:string,arg2:string,arg3:string):Promise<main.WebDAVSaveResult>;

export function ReadWorkspaceDirectory(arg1:string,arg2:string):Promise<main.WorkspaceDirectory>;

export function RenderingTestDocument():Promise<main.Document>;

export function SaveExportFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SaveResult>;

export function SaveFile(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SaveWebDAVFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.WebDAVSaveResult>;

export function SetLanguage(arg1:string,arg2:string):Promise<main.LanguageState>;

export function SetWindowTitle(arg1:string,arg2:boolean):Promise<void>;

export function UpdateMenuState(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function WelcomeDocument(arg1:string):Promise<main.Document>;
