// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateRecentDocument(arg1:string):Promise<void>;

export function BeginWebDAVMutation(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.WebDAVMutationPreparation>;

export function CancelQuitRequest():Promise<void>;

export function CancelUpdateDownload():Promise<void>;

export function CancelWebDAVMutation(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearRecentItems():Promise<void>;

export function CloseWebDAVDocument(arg1:string,arg2:string):Promise<void>;

export function CloseWebDAVWorkspace(arg1:string):Promise<void>;

export function CloseWorkspace(arg1:string):Promise<void>;

export function CloseWorkspaceDocument(arg1:string,arg2:string):Promise<void>;

export function CommitWebDAVDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CommitWebDAVRename(arg1:string,arg2:string,arg3:string):Promise<main.WorkspaceEntry>;

export function ConfirmQuit():Promise<void>;

export function ConnectSavedWebDAV(arg1:string):Promise<main.Workspace>;

export function ConnectWebDAV(arg1:main.WebDAVConfig):Promise<main.Workspace>;

export function CreateWebDAVDirectory(arg1:string,arg2:string):Promise<main.WorkspaceEntry>;

export function CreateWebDAVMarkdownFile(arg1:string,arg2:string):Promise<main.Document>;

export function CreateWorkspaceDirectory(arg1:string,arg2:string):Promise<main.WorkspaceEntry>;

export function CreateWorkspaceMarkdownFile(arg1:string,arg2:string):Promise<main.Document>;

export function DeleteSavedWebDAVConnection(arg1:string):Promise<void>;

export function DeleteWorkspaceEntry(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function DownloadUpdate(arg1:string):Promise<main.UpdateDownload>;

export function DownloadWebDAVWorkspaceFile(arg1:string,arg2:string):Promise<main.SaveResult>;

export function FetchPublicImage(arg1:string):Promise<main.ImageAssetData>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetLanguageSettings():Promise<main.LanguageState>;

export function GetThirdPartyNotices():Promise<string>;

export function ImportLocalImageData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ImageAsset>;

export function ImportWebDAVImageData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ImageAsset>;

export function LaunchUpdateInstaller():Promise<void>;

export function ListRecentMenuItems():Promise<Array<main.RecentMenuItem>>;

export function ListSavedWebDAVConnections():Promise<Array<main.SavedWebDAVConnection>>;

export function ListWebDAVDirectory(arg1:string,arg2:string):Promise<main.WorkspaceDirectory>;

export function LoadInitialDocument(arg1:string):Promise<main.Document>;

export function OpenDirectory():Promise<main.Workspace>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile():Promise<main.Document>;

export function OpenRecentDirectory(arg1:string):Promise<main.Workspace>;

export function OpenRecentFile(arg1:string):Promise<main.Document>;

export function OpenRecentWebDAV(arg1:string):Promise<main.RecentWebDAVConnection>;

export function OpenSourceRepository():Promise<void>;

export function OpenUpdatePage():Promise<void>;

export function OpenWebDAVFile(arg1:string,arg2:string):Promise<main.Document>;

export function OpenWorkspaceFile(arg1:string,arg2:string):Promise<main.Document>;

export function OverwriteWebDAVFile(arg1:string,arg2:string,arg3:string):Promise<main.WebDAVSaveResult>;

export function ReadWebDAVWorkspaceImage(arg1:string,arg2:string):Promise<main.ImageAssetData>;

export function ReadWorkspaceDirectory(arg1:string,arg2:string):Promise<main.WorkspaceDirectory>;

export function ReadWorkspaceImage(arg1:string,arg2:string):Promise<main.ImageAssetData>;

export function RememberLastPage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenameWorkspaceEntry(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.WorkspaceEntry>;

export function RenderingTestDocument():Promise<main.Document>;

export function ResolveLocalImage(arg1:string,arg2:string):Promise<main.ImageAssetData>;

export function ResolveWebDAVImage(arg1:string,arg2:string,arg3:string):Promise<main.ImageAssetData>;

export function SaveExportFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SaveResult>;

export function SaveFile(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SaveWebDAVConnection(arg1:main.WebDAVConnectionInput):Promise<main.SavedWebDAVConnection>;

export function SaveWebDAVFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.WebDAVSaveResult>;

export function SaveWorkspaceMarkdownFile(arg1:string,arg2:string,arg3:string):Promise<main.SaveResult>;

export function SelectImageFile():Promise<main.ImageAssetData>;

export function SetLanguage(arg1:string,arg2:string):Promise<main.LanguageState>;

export function SetWindowTitle(arg1:string,arg2:boolean):Promise<void>;

export function UpdateMenuState(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function UploadWebDAVWorkspaceFile(arg1:string,arg2:string):Promise<main.WorkspaceEntry>;

export function ValidateImageData(arg1:string,arg2:string,arg3:string):Promise<main.ImageAssetData>;

export function WelcomeDocument(arg1:string):Promise<main.Document>;
