// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateRecentDocument(arg1) {
  return window['go']['main']['App']['ActivateRecentDocument'](arg1);
}

export function BeginWebDAVMutation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BeginWebDAVMutation'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelQuitRequest() {
  return window['go']['main']['App']['CancelQuitRequest']();
}

export function CancelUpdateDownload() {
  return window['go']['main']['App']['CancelUpdateDownload']();
}

export function CancelWebDAVMutation(arg1, arg2) {
  return window['go']['main']['App']['CancelWebDAVMutation'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearRecentItems() {
  return window['go']['main']['App']['ClearRecentItems']();
}

export function CloseWebDAVDocument(arg1, arg2) {
  return window['go']['main']['App']['CloseWebDAVDocument'](arg1, arg2);
}

export function CloseWebDAVWorkspace(arg1) {
  return window['go']['main']['App']['CloseWebDAVWorkspace'](arg1);
}

export function CloseWorkspace(arg1) {
  return window['go']['main']['App']['CloseWorkspace'](arg1);
}

export function CloseWorkspaceDocument(arg1, arg2) {
  return window['go']['main']['App']['CloseWorkspaceDocument'](arg1, arg2);
}

export function CommitWebDAVDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitWebDAVDelete'](arg1, arg2, arg3);
}

export function CommitWebDAVRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitWebDAVRename'](arg1, arg2, arg3);
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function ConnectSavedWebDAV(arg1) {
  return window['go']['main']['App']['ConnectSavedWebDAV'](arg1);
}

export function ConnectWebDAV(arg1) {
  return window['go']['main']['App']['ConnectWebDAV'](arg1);
}

export function CreateWebDAVDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateWebDAVDirectory'](arg1, arg2);
}

export function CreateWebDAVMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['CreateWebDAVMarkdownFile'](arg1, arg2);
}

export function CreateWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspaceDirectory'](arg1, arg2);
}

export function CreateWorkspaceMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspaceMarkdownFile'](arg1, arg2);
}

export function DeleteSavedWebDAVConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedWebDAVConnection'](arg1);
}

export function DeleteWorkspaceEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteWorkspaceEntry'](arg1, arg2, arg3, arg4);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function DownloadWebDAVWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadWebDAVWorkspaceFile'](arg1, arg2);
}

export function FetchPublicImage(arg1) {
  return window['go']['main']['App']['FetchPublicImage'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLanguageSettings() {
  return window['go']['main']['App']['GetLanguageSettings']();
}

export function GetThirdPartyNotices() {
  return window['go']['main']['App']['GetThirdPartyNotices']();
}

export function ImportLocalImageData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportLocalImageData'](arg1, arg2, arg3, arg4);
}

export function ImportWebDAVImageData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportWebDAVImageData'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchUpdateInstaller() {
  return window['go']['main']['App']['LaunchUpdateInstaller']();
}

export function ListRecentMenuItems() {
  return window['go']['main']['App']['ListRecentMenuItems']();
}

export function ListSavedWebDAVConnections() {
  return window['go']['main']['App']['ListSavedWebDAVConnections']();
}

export function ListWebDAVDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListWebDAVDirectory'](arg1, arg2);
}

export function LoadInitialDocument(arg1) {
  return window['go']['main']['App']['LoadInitialDocument'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenRecentDirectory(arg1) {
  return window['go']['main']['App']['OpenRecentDirectory'](arg1);
}

export function OpenRecentFile(arg1) {
  return window['go']['main']['App']['OpenRecentFile'](arg1);
}

export function OpenRecentWebDAV(arg1) {
  return window['go']['main']['App']['OpenRecentWebDAV'](arg1);
}

export function OpenSourceRepository() {
  return window['go']['main']['App']['OpenSourceRepository']();
}

export function OpenUpdatePage() {
  return window['go']['main']['App']['OpenUpdatePage']();
}

export function OpenWebDAVFile(arg1, arg2) {
  return window['go']['main']['App']['OpenWebDAVFile'](arg1, arg2);
}

export function OpenWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['OpenWorkspaceFile'](arg1, arg2);
}

export function OverwriteWebDAVFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['OverwriteWebDAVFile'](arg1, arg2, arg3);
}

export function ReadWebDAVWorkspaceImage(arg1, arg2) {
  return window['go']['main']['App']['ReadWebDAVWorkspaceImage'](arg1, arg2);
}

export function ReadWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceDirectory'](arg1, arg2);
}

export function ReadWorkspaceImage(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceImage'](arg1, arg2);
}

export function RememberLastPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RememberLastPage'](arg1, arg2, arg3, arg4);
}

export function RenameWorkspaceEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RenameWorkspaceEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function RenderingTestDocument() {
  return window['go']['main']['App']['RenderingTestDocument']();
}

export function ResolveLocalImage(arg1, arg2) {
  return window['go']['main']['App']['ResolveLocalImage'](arg1, arg2);
}

export function ResolveWebDAVImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveWebDAVImage'](arg1, arg2, arg3);
}

export function SaveExportFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2, arg3, arg4);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SaveWebDAVConnection(arg1) {
  return window['go']['main']['App']['SaveWebDAVConnection'](arg1);
}

export function SaveWebDAVFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWebDAVFile'](arg1, arg2, arg3, arg4);
}

export function SaveWorkspaceMarkdownFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWorkspaceMarkdownFile'](arg1, arg2, arg3);
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SetLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetLanguage'](arg1, arg2);
}

export function SetWindowTitle(arg1, arg2) {
  return window['go']['main']['App']['SetWindowTitle'](arg1, arg2);
}

export function UpdateMenuState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateMenuState'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadWebDAVWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['UploadWebDAVWorkspaceFile'](arg1, arg2);
}

export function ValidateImageData(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateImageData'](arg1, arg2, arg3);
}

export function WelcomeDocument(arg1) {
  return window['go']['main']['App']['WelcomeDocument'](arg1);
}
