// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLanguageSettings() {
  return window['go']['main']['App']['GetLanguageSettings']();
}

export function LoadInitialDocument(arg1) {
  return window['go']['main']['App']['LoadInitialDocument'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenSourceRepository() {
  return window['go']['main']['App']['OpenSourceRepository']();
}

export function OpenUpdatePage() {
  return window['go']['main']['App']['OpenUpdatePage']();
}

export function SaveExportFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2, arg3, arg4);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SetLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetLanguage'](arg1, arg2);
}

export function SetWindowTitle(arg1, arg2) {
  return window['go']['main']['App']['SetWindowTitle'](arg1, arg2);
}

export function UpdateMenuState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMenuState'](arg1, arg2, arg3, arg4);
}

export function WelcomeDocument(arg1) {
  return window['go']['main']['App']['WelcomeDocument'](arg1);
}
