// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetLanguageSettings():Promise<main.LanguageState>;

export function LoadInitialDocument(arg1:string):Promise<main.Document>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile():Promise<main.Document>;

export function OpenSourceRepository():Promise<void>;

export function OpenUpdatePage():Promise<void>;

export function SaveExportFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SaveResult>;

export function SaveFile(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SetLanguage(arg1:string,arg2:string):Promise<main.LanguageState>;

export function SetWindowTitle(arg1:string,arg2:boolean):Promise<void>;

export function UpdateMenuState(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function WelcomeDocument(arg1:string):Promise<main.Document>;
